apiVersion: v1
kind: Service 
metadata:
  name: springboot 
spec:
  type: {{ .Values.service.type}}
  selector: 
    app: springboot
  ports:
    - port: {{ .Values.service.port}}
      targetPort: 8080