apiVersion: apps/v1
kind: Deployment 
metadata:
  name: springboot 
spec:   
  replicas: {{ .Values.replicaCount }}
  selector: 
    matchLabels: 
      app: springboot
  template:
    metadata:
      labels:
        app: springboot 
    spec:
      containers: 
        - name: springboot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          ports: 
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:{{ .Values.mysql.port }}/{{ .Values.mysql.database }}
            - name: SPRING_DATASOURCE_USERNAME 
              value: {{ .Values.mysql.user }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.mysql.password }}